name: Build and Deploy Go App to Minikube with Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"

      - name: Run tests
        run: go test ./...

      - name: Set Docker Env to Minikube
        run: |
          echo "Configuring Docker to use Minikube engine..."
          minikube -p minikube docker-env | Invoke-Expression

      - name: Build Docker image
        run: |
          docker build -t go-app:${{ github.sha }} .

        # THis code is for helm running via Docker
      - name: Helm Deploy (Dockerized)
        shell: powershell
        run: |
          docker run --rm `
            -v "$(pwd).Path:/apps" `
            -v "$($env:USERPROFILE)\.kube:/root/.kube" `
            -v "$($env:USERPROFILE)\.minikube:/root/.minikube" `
            -w /apps `
            alpine/helm:3.12.0 `
            upgrade --install go-app ./helm/go-app `
              --set image.repository=go-app `
              --set image.tag=${{ github.sha }} `
              --set image.pullPolicy=Never 





        # Below code will work for helm installed locally
      #- name: Helm Deploy
      #  shell: powershell
      #  run: |
      #    helm upgrade --install go-app ./helm/go-app `
      #    --set image.repository=go-app `
      #    --set image.tag=${{ github.sha }} `
      #    --set image.pullPolicy=Never
